# Generated by Django 6.0.5 on 2026-05-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("voter_id", models.CharField(max_length=25, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("voter", "Voter"), ("candidate", "Candidate")],
                        max_length=10,
                    ),
                ),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
